Update kubectl-wls
adding generator

diff --git a/kubectl-wls b/kubectl-wls
--- a/kubectl-wls
+++ b/kubectl-wls
@@ -1,18 +1,42 @@
 #!/bin/bash
 
+#Check kubectl client exists
+if ! command -v kubectl &> /dev/null
+then
+    printf "Kubectl client could not be found. Please install Kubectl client before running kubectl-exec.\nRefer to: https://kubernetes.io/docs/tasks/tools/\n\n"
+    exit 1
+fi
+
+#Check client major/minor versions
+kubectl_major_version=$(kubectl version --client -o yaml | grep -i "major" | awk '{ print $2 }' | sed 's/"//g')
+kubectl_minor_version=$(kubectl version --client -o yaml | grep -i "minor" | awk '{ print $2 }' | sed 's/"//g')
+
+if [[ $kubectl_major_version -gt 1 ]] || [[ $kubectl_major_version -eq 1 && $kubectl_minor_version -ge 18 ]]
+then
+        use_generator=false
+        echo "Kuberetes client version is $kubectl_major_version.$kubectl_minor_version. Generator will not be used since it is deprecated."
+elif [[ $kubectl_major_version -eq 1 && $kubectl_minor_version -lt 18 ]]
+then
+        use_generator=true
+        echo "Kuberetes client version is $kubectl_major_version.$kubectl_minor_version. Generator will be used."
+else
+        echo "Invalid kubectl version, exiting."
+        exit 1
+fi
+
 #Usage message
 usage()
 {
         echo 'Interactive:'
-        echo '$ kubectl-wls'
+        echo '$ kubectl-exec'
         echo " "
         echo 'Non-Interactive'
-        echo '$ kubectl-wls NODE'
+        echo '$ kubectl-exec NODE'
         echo " "
-        echo "Example: kubectl-wls minikube"
+        echo "Example: kubectl-exec minikube"
         echo " "
-        echo "If you are running wls as a script"
-        echo "./kubectl-wls"
+        echo "If you are running as a script"
+        echo "./kubectl-exec"
         exit 0
 }
 
@@ -30,7 +54,7 @@ if [ -z "$1" ]; then
         for i in "${!nodenumber[@]}"; do
           printf "$i ${nodenumber[i]} \n"
         done
-          
+        
         read -p "Enter the node number: " NODE_INDEX
         NODE=${nodenumber[NODE_INDEX]}
 
@@ -72,9 +96,13 @@ EOT
 )"
 
 echo "creating pod \"$POD\" on node \"$NODE\""
-kubectl run --rm --image $IMAGE --overrides="$OVERRIDES" --generator=run-pod/v1 -ti "$POD"
+if [ $use_generator = true ]
+then
+        kubectl run --rm --image $IMAGE --overrides="$OVERRIDES" --generator=run-pod/v1 -ti "$POD"
+else
+        kubectl run --rm --image $IMAGE --overrides="$OVERRIDES" -ti "$POD"
+fi
 }
-
 
 #windows function to ssh to windows nodes
 WINDOWSNODES () {
@@ -115,7 +143,14 @@ EOT
 )"
 
 echo "creating pod \"$POD\" for windows ssh"
-kubectl run --rm --image $IMAGE --overrides="$OVERRIDES" --generator=run-pod/v1 -ti "$POD"
+
+if [ $use_generator = true]
+then
+        kubectl run --rm --image $IMAGE --overrides="$OVERRIDES" --generator=run-pod/v1 -ti "$POD"
+else
+        kubectl run --rm --image $IMAGE --overrides="$OVERRIDES" -ti "$POD"
+fi
+
 }
 
 #Evaluate if windows node.
